#!/usr/bin/env bash
# Concatenate vault/rules/*.md into ~/.claude/CLAUDE.user.md
set -euo pipefail

REPO_DIR="${REPO_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
RULES_DIR="${REPO_DIR}/vault/rules"
OUT="${HOME}/.claude/CLAUDE.user.md"

if [[ ! -d "${RULES_DIR}" ]]; then
  echo "[vault] no rules dir: ${RULES_DIR}" >&2
  exit 0
fi

mkdir -p "$(dirname "${OUT}")"

{
  echo "# User Rules"
  echo ""
  echo "<!-- AUTO-GENERATED by vault/scripts/build.sh — edit vault/rules/*.md instead -->"
  echo "<!-- Build time: $(date -u +%Y-%m-%dT%H:%M:%SZ) -->"
  echo ""

  shopt -s nullglob
  for f in "${RULES_DIR}"/*.md; do
    cat "${f}"
    echo ""
  done
  shopt -u nullglob
} > "${OUT}"

echo "[vault] built → ${OUT}"
